/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBiActivity: typeof import('~icons/bi/activity')['default']
    IFaAdjust: typeof import('~icons/fa/adjust')['default']
    IFaAngellist: typeof import('~icons/fa/angellist')['default']
    IFaCheck: typeof import('~icons/fa/check')['default']
    IFaClone: typeof import('~icons/fa/clone')['default']
    IFaCoffee: typeof import('~icons/fa/coffee')['default']
    IFaCope: typeof import('~icons/fa/cope')['default']
    IFaCopy: typeof import('~icons/fa/copy')['default']
    IFaGithub: typeof import('~icons/fa/github')['default']
    IFaGitlab: typeof import('~icons/fa/gitlab')['default']
    IFaHome: typeof import('~icons/fa/home')['default']
    IFaImage: typeof import('~icons/fa/image')['default']
    IFaLink: typeof import('~icons/fa/link')['default']
    IFaLinkedinSquare: typeof import('~icons/fa/linkedin-square')['default']
    IFaMoonO: typeof import('~icons/fa/moon-o')['default']
    IFaSolidMoon: typeof import('~icons/fa-solid/moon')['default']
    IFaSolidSun: typeof import('~icons/fa-solid/sun')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
