/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IFaAdjust: typeof import('~icons/fa/adjust')['default']
    IFaCheck: typeof import('~icons/fa/check')['default']
    IFaClone: typeof import('~icons/fa/clone')['default']
    IFaCoffee: typeof import('~icons/fa/coffee')['default']
    IFaGithub: typeof import('~icons/fa/github')['default']
    IFaGitlab: typeof import('~icons/fa/gitlab')['default']
    IFaHome: typeof import('~icons/fa/home')['default']
    IFaImage: typeof import('~icons/fa/image')['default']
    IFaLinkedinSquare: typeof import('~icons/fa/linkedin-square')['default']
    IFaSolidMoon: typeof import('~icons/fa-solid/moon')['default']
    IFaSolidSun: typeof import('~icons/fa-solid/sun')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
